// creating shortcut for printing
const p = console.log;

// get the references to interactive HTML elements
const ctrlBtns = document.querySelectorAll('.controls button');
const cntnr = document.querySelector('.container');
let btnsArray = [
    ctrlBtns[0],
    ctrlBtns[1],
    ctrlBtns[2]
];

// create array that will store the data
let pages = [
    {
        heading: "Wind Power Generation",
        bodyText: "Wind power generation is the main application of wind energy, refers to the wind power as a power to drive the generator to convert wind energy into electricity.",
        thumb: "./images/wind.jpg"
    },
    {
        heading: "Hydropower",
        bodyText: "hydropower is generated by the Earth's water cycle, including evaporation, rainfall, tides and the force of water running through a dam.",
        thumb: "./images/water.jpg"
    },
    {
        heading: "Solar power",
        bodyText: "The most prevalent type of renewable energy, solar power is typically produced using photovoltaic cells, which capture sunlight and turn it into electricity.",
        thumb: "./images/solar.jpg"
    }
];
// create function that handles click-event
function  clickBtn(ev) {
    
    // Brightspsce Ref: Week 6
    let clickedButton = ev.target;
    
    // MDN Ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf
    let index = btnsArray.indexOf(clickedButton);
    p(index);
    
    // MDN Ref: https://developer.mozilla.org/en-US/docs/Web/API/Element
    p(clickedButton.id);
    // handle moving id-active to the currently clicked button 

        // remove currently present id="active"
        for (let i = 0; i < ctrlBtns.length; i++){
            // claiming that current element in the loop containe attribute
            if(btnsArray[i].id){
                // MDN ref: https://developer.mozilla.org/en-US/docs/Web/API/Element/removeAttribute
                btnsArray[i].removeAttribute('id');
            }  
        }

        // assign id="active" to the currently clicked button
        clickedButton.id = 'active';    
    
    // load the corresponding data into <div class="container"></div>
    cntnr.innerHTML = `
        <h2>${pages[index].heading}</h2>
        <p class = "bodyText">${pages[index].bodyText}</p>
        <figure>
        <img src=${pages[index].thumb} alt="${pages[index].heading}">
        </figure>
    `;
}
// register your buttons for click event
for(let i = 0; i<ctrlBtns.length; i++){ 
    ctrlBtns[i].addEventListener('click', clickBtn);  
}
